name: Rebuild demo repo

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Optional: override target repo URL (example: github.com:linearb-customer-solutions/gitstream-demo.git)'
        required: false
  schedule:
    - cron: '3 3 * * *'  # Runs daily at 03:03 UTC

jobs:
  rebuild:
    runs-on: ubuntu-latest
    env:
      # These variables are set in the GitHub repository settings
      # Should be valid GitHub usernames in the same organization as the demo repo
      AUTH_SERVICE_COMMITTER_USERNAME: ${{ vars.AUTH_SERVICE_COMMITTER_USERNAME }}
      BILLING_SERVICE_COMMITTER_USERNAME: ${{ vars.BILLING_SERVICE_COMMITTER_USERNAME }}
      ORDERS_SERVICE_COMMITTER_USERNAME: ${{ vars.ORDERS_SERVICE_COMMITTER_USERNAME }}
      META_COMMITTER_USERNAME: ${{ vars.META_COMMITTER_USERNAME }}
      FRONTEND_COMMITTER_USERNAME: ${{ vars.FRONTEND_COMMITTER_USERNAME }}
      PR_COMMITTER_USERNAME: ${{ vars.PR_COMMITTER_USERNAME }}
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      TARGET_REPO: https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@${{ inputs.target_repo || vars.TARGET_REPO }}

    steps:
      - name: Checkout repo @ main
        uses: actions/checkout@v4
        with:
          path: 'gitstream-automation-demo-main' # script below uses this path

      - name: Checkout repo @ new-feature
        uses: actions/checkout@v4
        with:
          path: 'gitstream-automation-demo-new-feature' # script below uses this path
          ref: 'new-feature'

      - name: Run rewrite script
        run: ./gitstream-automation-demo-main/bootstrap_demo_repo.sh
